#!/bin/bash
#$ -N %N%
#$ -pe smp 8
#$ -q gpu
#$ -l gpu=2

module purge
# Increase the MPI buffer
export P4_GLOBMEMSIZE=268435456

# export CUDA_VISIBLE_DEVICES="0,1"
export MV2_ENABLE_AFFINITY=0

module load amber/18.0

mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md1_heat.in    \
				  -o md1_heat.out          \
				  -c md0_min2.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md1_heat.rst          \
				  -x md1_heat.mdcrd		\
				  -ref md0_min2.rst

mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md2a_eqNPT_restrained.in    \
				  -o md2a_eqNPT_restrained.out          \
				  -c md1_heat.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md2a_eqNPT_restrained.rst          \
				  -x md2a_eqNPT_restrained.mdcrd	\
				  -ref md1_heat.rst
				  
mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md2b_eqNPT_restrained.in    \
				  -o md2b_eqNPT_restrained.out          \
				  -c md2a_eqNPT_restrained.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md2b_eqNPT_restrained.rst          \
				  -x md2b_eqNPT_restrained.mdcrd		\
				  -ref md2a_eqNPT_restrained.rst
				  
mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md2c_eqNPT_restrained.in    \
				  -o md2c_eqNPT_restrained.out          \
				  -c md2b_eqNPT_restrained.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md2c_eqNPT_restrained.rst          \
				  -x md2c_eqNPT_restrained.mdcrd		\
				  -ref md2b_eqNPT_restrained.rst
				  
mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md2d_eqNPT_restrained.in    \
				  -o md2d_eqNPT_restrained.out          \
				  -c md2c_eqNPT_restrained.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md2d_eqNPT_restrained.rst          \
				  -x md2d_eqNPT_restrained.mdcrd		\
				  -ref md2c_eqNPT_restrained.rst
				  
mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md2e_eqNPT_restrained.in    \
				  -o md2e_eqNPT_restrained.out          \
				  -c md2d_eqNPT_restrained.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md2e_eqNPT_restrained.rst          \
				  -x md2e_eqNPT_restrained.mdcrd	\
				  -ref md2d_eqNPT_restrained.rst

mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md3_eqNPT.in    \
				  -o md3_eqNPT.out          \
				  -c md2e_eqNPT_restrained.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md3_eqNPT.rst          \
				  -x md3_eqNPT.mdcrd

bash equalize_volume.sh

mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
				  -i md4_eqNVT.in    \
				  -o md4_eqNVT.out          \
				  -c md3_eqNPT-eq.rst              \
				  -p TI-merged_WAT.prmtop          \
				  -r md4_eqNVT.rst          \
				  -x md4_eqNVT.mdcrd

sleep 10
exit 0
