#!/bin/bash
#$ -N %N%
#$ -pe smp 8
#$ -q gpu

module purge
# Increase the MPI buffer
export P4_GLOBMEMSIZE=268435456

# export CUDA_VISIBLE_DEVICES="0,1"
# export MV2_ENABLE_AFFINITY=0

module load amber/18.0

export MDINP=0
export MDCUR=1
export MDJOB=1

while [ $MDCUR -le $MDJOB ]; do
  mpirun --bind-to none -np $NSLOTS pmemd.cuda.MPI -O \
                      -i prod.in    \
                      -o Prod_$MDCUR.out          \
                      -c Prod_$MDINP.rst              \
                      -p TI-merged_WAT.prmtop          \
                      -r Prod_$MDCUR.rst          \
                      -x Prod_$MDCUR.mdcrd	  \
		      -e Prod_$MDCUR.en

  let MDINP=MDCUR
  let MDCUR=MDCUR+1
done

sleep 10
exit 0
